### ISSUE TITLE
Handle underlying change notifications?

### ISSUE THREAD

**Issue by marbetschar** [LucianoPolit/RepositoryKit#1]
Wow, your RepositoryKit looks really promising, thanks for all the work!!

I'm currently evaluating new ways in order to overhaul the architecture of quite a complex app. This app will have a local database as master repository (I'm opting for Realm).

How would I notify the UI about changes occured in the database using `RepositoryKit`? Does `RepositoryKit` support registering callbacks or something?

FYI: Here's the notification stuff from Realm: https://realm.io/docs/swift/latest/#notifications

**Comment by LucianoPolit** [comment]
Hey Marco, I'm glad to see you interested!

The way of doing that with collections is implementing a `NSFetchedResultsController` and its delegate (`NSFetchedResultsControllerDelegate`). On the [example](https://github.com/LucianoPolit/RepositoryKit/tree/master/Example/Source) you can see how to do it. Basically, the [CoreDataTableViewController](https://github.com/LucianoPolit/RepositoryKit/blob/master/Example/Source/CoreDataTableViewController.swift) is responsible of updating the UI when needed and the [UsersTableViewController](https://github.com/LucianoPolit/RepositoryKit/blob/master/Example/Source/UserTableViewController.swift) only has to configure the `NSFetchedResultsController`.

If you need the changes of a particular object, I would recommend you to implement an observer.

Right now, `RepositoryKit` is an organization layer. Therefore, you should interact with the database like you do with `CoreData`. Maybe, in a future, some fancy utils can be implemented.

I hope it has been helpful! Don't hesitate to ask if you have any other doubts!

**Comment by marbetschar** [comment]
Thanks for your detailed answers, I really appreciate them!

> Right now, RepositoryKit is an organization layer. Therefore, you should interact with the database like you do with CoreData. Maybe, in a future, some fancy utils can be implemented.

I don't exactly understand what you mean by saying "RepositoryKit is an organization layer": Are you suggesting I'll should deal with the database change notifications directly from within my UI layer? Having the ViewController listening to change events using the storage layer API (`NSFetchedResultsControllerDelegate`)? From what I've understood this would violate the main goal of the repository pattern since this does not abstract away the storage layer?

I can see how this would be easier to implement, since no abstraction layer is added. But since I will have to deal with several different kinds of repositories, which hold their own subset of data and may change at any time, I'm not quite sure if this is the right way to go.

Or is this the way you are suggesting, because you put all data in the local repository first and have the UI dealing with only this repo anyway - and therefore you are willing to violate the pattern in favour of simplicity here?

**Comment by LucianoPolit** [comment]
Yeah, I understand that it's not completed abstracted, but it has a reasoning there. The `Data Model` (the graph) and the `NSFetchedResultController` are two really powerful tools of `CoreData` to use around your project.

On the other side, what it is really abstracted is the way to operate with the database (you forget how to CRUD, contexts, persistence, etc).

`Or is this the way you are suggesting, because you put all data in the local repository first and have the UI dealing with only this repo anyway - and therefore you are willing to violate the pattern in favour of simplicity here?`

Pretty nice described what I think here. I just trust that the local repo has the information that I need.
