### ISSUE TITLE
Missing argument for parameter #1 in call

### ISSUE THREAD

**Issue by marbetschar** [LucianoPolit/RepositoryKit#4]
`RepositoryKit` does not compile using Xcode 9.0 (9A235). It throws the following error at several locations:

<img width="969" alt="bildschirmfoto 2017-10-16 um 23 26 14" src="https://user-images.githubusercontent.com/392542/31636123-8e37f0f2-b2c9-11e7-867e-246b966068d7.png">

**Comment by marbetschar** [comment]
Seems like this is related to [SE-0110: Distinguish between single-tuple and multiple-argument function types](https://swift.org/migration-guide-swift4/#se-0110-distinguish-between-single-tuple-and-multiple-argument-function-types) of Swift 4.

**Comment by LucianoPolit** [comment]
Hey, yes, I knew it. I just needed some free time to migrate it. I'll probably release a new version supporting swift 4 today.
