### ISSUE TITLE
Make RepositoryKit CoreData agnostic?

### ISSUE THREAD

**Issue by marbetschar** [LucianoPolit/RepositoryKit#6]
I've had a look at the `realm` branch, and it seems one has to implement quite a few protocol methods which are related to `CoreData` - which of course are not usefull in terms of `Realm`.

What do you think of redesigning RepositoryKit in order to make it `CoreData` agnostic as first step? Feels like just getting Realm working without rethinking RepositoryKit may lead to further issues down the road.

**Comment by LucianoPolit** [comment]
Oh, in fact, they are not needed. I conformed that protocols to reuse other repositories that requires some `Storage` (like the `SynchronizableRepository`). But it was not working, so I decided to stop spending extra time on it. Anyway, the `CRUDRealmRepository` works without that conformances (without the protocols named something with `Storage`, like `StorageRepository`). If you need help with that, just ask it :)

And the answer to the question is a big `NO`. When I designed `RepositoryKit` I wanted to not depend of external dependencies, just what is provided by default and the `PromiseKit` (no `Alamofire`, no `Realm`, no that kind of `frameworks`). It was designed in a way that if you want to use this external dependencies, you should implement them apart. So, the only way of interact to the local storage without an external dependency was `CoreData`, therefore, it depends directly on its behavior.

**Comment by LucianoPolit** [comment]
Yeah, maybe it could be a chance to improve it, or maybe it should keep as it is. Sorry mate but I do not have more free time to deal with `Realm`. Nevertheless, it would be a pleasure if you want to contribute to the project making a PR.
